### ISSUE TITLE
Mark mod as 1.20.1-compatible

### ISSUE THREAD

**Issue by anoomolu** [wendeburg/deterministic-xp-bottle#1]
Hiya, been looking for a mod that allows xp bottles to be buffed, so thank you for making this.

I manually edited the fabric-mod.json to allow the mod to run on 1.20.1, and it seems to work just fine, tested by:
- setting level to 30 using /xp set player 30 levels
- using an xp bottle
- checking whether the /xp query player points matches with the config setting.

Would you be able to mark the mod as 1.20.1 compatible, so it shows up on third-party launchers running that specific version? Cheers.

**Comment by wendeburg** [comment]
Hi, I made a new release for minecraft 1.20.1: https://modrinth.com/mod/deterministic-xp-bottles/version/0.1-1.20.1

Should I also mark the 1.20.2 version as 1.20.1 compatible? I'm new to making mods so IDK if that could cause any problems due to me using modmenu 8.0.0 as a dependency in the build.gradle.

Also one more question: Would it be better if the XP dropped by the xp bottles wasn't limited to 100 points?

Cheers.
